### ISSUE TITLE
missing node.dll and ffmpeg.dll

### ISSUE THREAD

**Issue by MickyRocket** [RandScullard/photo-screen-saver#1]
Hello there!
I really liked the idea of making a screensaver with electron. So I have made one. But it only runs on my win7-machine, where I created it on. I then copied the finished .scr-file to my win10-laptop. But it doesn't start. It keeps telling me, that node.dll and ffmpeg.dll were missing. Am I missing something? Isn't this thing designed to deliver one single executable file in the end? It would be very nice if somebody could help me on this. Thanks!

**Comment by RandScullard** [comment]
When I deploy to another machine, I copy the entire `photo-screen-saver\package\photo-screen-saver-win32-x64` folder tree to the destination machine. I think if you do that, everything will work fine.

**Comment by MickyRocket** [comment]
Yep I get that, but if you want to install a screensaver in the system32-folder, you don't want to spam it with the whole package-files. I would rather prefer to store the screensaver-package in some more adequate place for it on the harddrive, and then have a .scr-file to execute it in the system32-folder. Do you maybe have any idea oh how to achieve this?

**Comment by RandScullard** [comment]
Why do you want to put it in system32? I just put everything in a folder under Program Files.

**Comment by MickyRocket** [comment]
It is possible to place the whole package somewhere on the harddrive and the install the .scr-file. I already know about that. But if a user once selects another screensaver and closes the screensaver-settings the screensaver disappears from the list of all screensavers to chose from. And if he wants to activate it again he needs to reinstall the .scr-file which is not really user-friendly. To avoid this it is necessary to put the .scr-file into the system32-folder... Then the screensaver will always be listed in the list...

**Comment by RandScullard** [comment]
Oh, I see. That wasn't a scenario I've needed to deal with so far. I'll leave this issue open in case anyone else has a suggestion.

**Comment by RandScullard** [comment]
Based on my research, Windows is hard-coded to build the list of screen savers in the Screen Saver Settings window from the set of .scr files in the following folders:

- Windows
- Windows\System32
- Windows\SysWOW64

Electron requires that all generated files live in the same folder as the .scr file, so if you put the .scr file in one of these folders, you'd have to put all the other files from photo-screen-saver-win32-x64 in there too. I would **not recommend** doing this.

If you really want to solve this, you could code up a small executable named "Photo Screen Saver.scr" that just executes photo-screen-saver.exe from the photo-screen-saver-win32-x64 folder. Put it in your System32 folder and it will show up in the list.
