### ISSUE TITLE
Uncaught ReferenceError: exports is not defined at index.js:2

### ISSUE THREAD

**Issue by greym0uth** [RandScullard/photo-screen-saver#2]
Not quite sure what is wrong, I have the most recent version of grunt-cli and node. I get this issue when I build the project right after cloning it and not editing it in any way (other than enabling devtools).

Index.js:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true }); // This is the line causing the issue.
var $ = require("jquery");
var https = require("https");
var vm = require("vm");
var concat = require("concat-stream");
var fs = require("fs");
var imageUrls = [];
var imageNum = 0;
```

**Comment by greym0uth** [comment]
After a bit of research I found that this could be a problem in the compiling of the project. Maybe something with grunt could be causing this issue. I'm not too familiar with grunt, and I'm not quite sure what in grunt could be causing this issue.

**Comment by RandScullard** [comment]
It looks like there was a change in TypeScript 2.2 (https://github.com/Microsoft/TypeScript/issues/14351) that broke the build. Please try the following:

Edit src/index.html and add this just before the script tag that includes index.js:

    <script>
    // TypeScript 2.2 requires 'exports' global variable.
    var exports = {};
    </script>

Re-run `grunt` and `npm start`. This fixed it for me -- if it works for you too, I'll commit the change.

**Comment by greym0uth** [comment]
Yup that worked! Im going to leave it open, not sure if you want to close this until you make the commit. Thanks!

**Comment by RandScullard** [comment]
Thanks for letting me know about this!
